language: c
compiler:
  - gcc

before_script:
  - sudo add-apt-repository -y ppa:fkrull/deadsnakes
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo apt-get update -qq
  - sudo apt-get install -y python3.3 python3 gcc-4.7 gcc-multilib gcc-arm-none-eabi qemu-system mingw32
  # For teensy build
  - sudo apt-get install realpath

script:
  - make -C minimal test
  - make -C unix CC=gcc-4.7
  - make -C unix-cpy CC=gcc-4.7
  - make -C bare-arm
  - make -C qemu-arm test
  - make -C stmhal
  - make -C stmhal -B MICROPY_PY_WIZNET5K=1 MICROPY_PY_CC3K=1
  - make -C stmhal BOARD=STM32F4DISC
  - make -C teensy
  - make -C windows CROSS_COMPILE=i586-mingw32msvc-

  - (cd tests && MICROPY_CPYTHON3=python3.3 ./run-tests)
  - (cd tests && MICROPY_CPYTHON3=python3.3 ./run-tests --emit native)

after_failure:
  - (cd tests && for exp in *.exp; do testbase=$(basename $exp .exp); echo -e "\nFAILURE $testbase"; diff -u $testbase.exp $testbase.out; done)
  - (grep "FAIL" qemu-arm/build/console.out)
