language: c
compiler:
  - gcc

before_script:
  - sudo add-apt-repository -y ppa:fkrull/deadsnakes
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo apt-get update -qq
  - sudo apt-get install -y python3.3 python3 gcc-4.7 gcc-arm-none-eabi

script:
  - make -C unix CC=gcc-4.7
  - make -C unix-cpy CC=gcc-4.7
  - make -C bare-arm
  - make -C stmhal
  - cd tests && MICROPY_CPYTHON3=python3.3 ./run-tests

after_failure:
  - cat tests/memoryerror.py.exp
  - cat tests/memoryerror.py.out
  - cd tests && for exp in *.exp; do testbase=$(basename $exp .exp); echo -e "\nFAILURE $testbase"; diff $testbase.exp $testbase.out; done
