contact_links:
  - name: ðŸ”— Adafruit Forum
    url: https://forums.adafruit.com/
    about: Official Adafruit technical support forum. Good for getting help on getting a project working.
  - name: ðŸ”— Adafruit Discord
    url: https://adafru.it/discord
    about: Unofficial chat with many helpful folks and normally prompt replies.
