name: Build CI

on:
  push:
  pull_request:
  release:
    types: [published]
  check_suite:
    types: [rerequested]

jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Install deps
      run: |
        sudo apt-get install -y eatmydata
        sudo eatmydata apt-get install -y gettext librsvg2-bin mingw-w64
        pip install requests sh click setuptools cpp-coveralls Sphinx sphinx-rtd-theme recommonmark sphinxcontrib-svg2pdfconverter polib pyyaml
    - name: Versions
      run: |
        gcc --version
        python3 --version
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: CircuitPython version
      run: git describe --dirty --always --tags
    - name: Build mpy-cross
      run: make -C mpy-cross -j2
    - name: Build unix port
      run: |
        make -C ports/unix deplibs -j2
        make -C ports/unix -j2
        make -C ports/unix coverage -j2
    - name: Test all
      run: MICROPY_CPYTHON3=python3.5 MICROPY_MICROPYTHON=../ports/unix/micropython_coverage ./run-tests -j1
      working-directory: tests
    - name: Print failure info
      run: |
        for exp in *.exp;
        do testbase=$(basename $exp .exp);
        echo -e "\nFAILURE $testbase";
        diff -u $testbase.exp $testbase.out;
        done
      working-directory: tests
      if: failure()
    - name: Native Tests
      run: MICROPY_CPYTHON3=python3.5 MICROPY_MICROPYTHON=../ports/unix/micropython_coverage ./run-tests -j1 --emit native
      working-directory: tests
    - name: mpy Tests
      run: MICROPY_CPYTHON3=python3.5 MICROPY_MICROPYTHON=../ports/unix/micropython_coverage ./run-tests -j1 --via-mpy -d basics float
      working-directory: tests
    - name: Docs
      run: sphinx-build -E -W -b html . _build/html
    - name: Translations
      run: make check-translate
    - name: New boards check
      run: python3 -u ci_new_boards_check.py
      working-directory: tools

    - name: Build mpy-cross.static-raspbian
      run: make -C mpy-cross -j2 -f Makefile.static-raspbian
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: mpy-cross.static-raspbian
        path: mpy-cross/mpy-cross.static-raspbian

    - name: Build mpy-cross.static
      run: make -C mpy-cross -j2 -f Makefile.static
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: mpy-cross.static-amd64-linux
        path: mpy-cross/mpy-cross.static

    - name: Build mpy-cross.static-mingw
      run: make -C mpy-cross -j2 -f Makefile.static-mingw
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: mpy-cross.static-x64-windows
        path: mpy-cross/mpy-cross.static.exe

  mpy-cross-mac:
    runs-on: macos-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Install deps
      run: |
        brew link --force gettext
    - name: Versions
      run: |
        gcc --version
        python3 --version
        msgfmt --version
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: CircuitPython version
      run: git describe --dirty --always --tags
    - name: Build mpy-cross
      run: make -C mpy-cross -j2
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: mpy-cross-macos-catalina
        path: mpy-cross/mpy-cross

  build-arm:
    runs-on: ubuntu-16.04
    needs: test
    strategy:
      fail-fast: false
      matrix:
        board:
        - "aramcon_badge_2019"
        - "arduino_mkr1300"
        - "arduino_mkrzero"
        - "arduino_nano_33_ble"
        - "arduino_zero"
        - "bast_pro_mini_m0"
        - "capablerobot_usbhub"
        - "catwan_usbstick"
        - "circuitbrains_basic_m0"
        - "circuitbrains_deluxe_m4"
        - "circuitplayground_bluefruit"
        - "circuitplayground_express"
        - "circuitplayground_express_crickit"
        - "circuitplayground_express_displayio"
        - "clue_nrf52840_express"
        - "cp32-m4"
        - "datalore_ip_m4"
        - "datum_distance"
        - "datum_imu"
        - "datum_light"
        - "datum_weather"
        - "electronut_labs_blip"
        - "electronut_labs_papyr"
        - "escornabot_makech"
        - "espruino_pico"
        - "espruino_wifi"
        - "feather_bluefruit_sense"
        - "feather_m0_adalogger"
        - "feather_m0_basic"
        - "feather_m0_express"
        - "feather_m0_express_crickit"
        - "feather_m0_rfm69"
        - "feather_m0_rfm9x"
        - "feather_m0_supersized"
        - "feather_m4_express"
        - "feather_m7_1011"
        - "feather_mimxrt1011"
        - "feather_mimxrt1062"
        - "feather_nrf52840_express"
        - "feather_radiofruit_zigbee"
        - "feather_stm32f405_express"
        - "gemma_m0"
        - "grandcentral_m4_express"
        - "hallowing_m0_express"
        - "hallowing_m4_express"
        - "imxrt1010_evk"
        - "imxrt1020_evk"
        - "imxrt1060_evk"
        - "itsybitsy_m0_express"
        - "itsybitsy_m4_express"
        - "itsybitsy_nrf52840_express"
        - "kicksat-sprite"
        - "makerdiary_nrf52840_mdk"
        - "makerdiary_nrf52840_mdk_usb_dongle"
        - "meowbit_v121"
        - "meowmeow"
        - "metro_m0_express"
        - "metro_m4_airlift_lite"
        - "metro_m4_express"
        - "metro_nrf52840_express"
        - "mini_sam_m4"
        - "monster_m4sk"
        - "ndgarage_ndbit6"
        - "ohs2020_badge"
        - "openbook_m4"
        - "particle_argon"
        - "particle_boron"
        - "particle_xenon"
        - "pca10056"
        - "pca10059"
        - "pewpew10"
        - "pewpew_m4"
        - "pirkey_m0"
        - "pyb_nano_v2"
        - "pybadge"
        - "pybadge_airlift"
        - "pyboard_v11"
        - "pycubed"
        - "pygamer"
        - "pygamer_advance"
        - "pyportal"
        - "pyportal_titano"
        - "pyruler"
        - "robohatmm1_m4"
        - "sam32"
        - "seeeduino_xiao"
        - "serpente"
        - "shirtty"
        - "snekboard"
        - "sparkfun_lumidrive"
        - "sparkfun_nrf52840_mini"
        - "sparkfun_qwiic_micro_no_flash"
        - "sparkfun_qwiic_micro_with_flash"
        - "sparkfun_redboard_turbo"
        - "sparkfun_samd21_dev"
        - "sparkfun_samd21_mini"
        - "spresense"
        - "stm32f411ce_blackpill"
        - "stm32f411ve_discovery"
        - "stm32f412zg_discovery"
        - "stm32f4_discovery"
        - "stringcar_m0_express"
        - "teensy40"
        - "teknikio_bluebird"
        - "trellis_m4_express"
        - "trinket_m0"
        - "trinket_m0_haxpress"
        - "uchip"
        - "ugame10"
        - "winterbloom_sol"
        - "xinabox_cc03"
        - "xinabox_cs11"

    steps:
    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Install deps
      run: |
        sudo apt-get install -y gettext
        pip install requests sh click setuptools awscli
        wget https://adafruit-circuit-python.s3.amazonaws.com/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
        sudo tar -C /usr --strip-components=1 -xaf gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
    - name: Versions
      run: |
        gcc --version
        arm-none-eabi-gcc --version
        python3 --version
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: mpy-cross
      run: make -C mpy-cross -j2
    - name: build
      run: python3 -u build_release_files.py
      working-directory: tools
      env:
        BOARDS: ${{ matrix.board }}
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ matrix.board }}
        path: bin/${{ matrix.board }}
    - name: Upload to S3
      run: "[ -z \"$AWS_ACCESS_KEY_ID\" ] || aws s3 cp bin/ s3://adafruit-circuit-python/bin/ --recursive --no-progress --region us-east-1"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      if: github.event_name == 'push' || (github.event_name == 'release' && (github.event.action == 'published' || github.event.action == 'rerequested'))
    - name: Install upload deps
      run: |
        pip install uritemplate
    - name: Upload to Release
      run: "[ -z \"$ADABOT_GITHUB_ACCESS_TOKEN\" ] || python3 -u upload_release_files.py"
      working-directory: tools
      env:
        UPLOAD_URL: ${{ github.event.release.upload_url }}
        ADABOT_GITHUB_ACCESS_TOKEN: ${{ secrets.BLINKA_GITHUB_ACCESS_TOKEN }}
      if: github.event_name == 'release' && (github.event.action == 'published' || github.event.action == 'rerequested')
