name: Check spelling with codespell

on: [push, pull_request]

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    # codespell version should be kept in sync with .pre-commit-config.yml
    - run: pip install --user codespell==2.4.1 tomli
    - run: codespell
    # additionally check for misspelling of "MicroPython"
    - run: |
        if git grep -n Micropython -- ":(exclude).github/workflows/codespell.yml"; then
            echo "Please correct capitalisation of MicroPython on the above lines"
            exit 1
        fi
