name: Build lv_micropython esp32 port

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        board: [GENERIC_SPIRAM]
    steps:
    - uses: actions/checkout@v2
    - uses: Install ESPIDF
      run: | 
        git clone https://github.com/espressif/esp-idf.git
        git -C esp-idf checkout v4.0.2
        git -C esp-idf submodule update --init components/bt/controller/lib components/bt/host/nimble/nimble components/esp_wifi/lib_esp32 components/esptool_py/esptool components/lwip/lwip components/mbedtls/mbedtls
        ./esp-idf/install.sh
    - name: Set ESPIDF path
      run: echo "ESPIDF=$PWD/esp-idf" >> $GITHUB_ENV
    - name: Update submodules
      run: git submodule update --init --recursive  
    - name: Build mpy-cross
      run: make -j $(nproc) -C mpy-cross
    - name: Build ${{ matrix.board }}
      run: make -j $(nproc) -C ports/esp32 BOARD=${{ matrix.board }} LV_CFLAGS="-DLV_COLOR_DEPTH=16 -DLV_COLOR_16_SWAP=1"
    - uses: actions/upload-artifact@v2
      if: ${{ env.GITHUB_EVENT_NAME }} == 'push'
      with:
        name: ${{ matrix.board }}.hex
        path: ports/esp32/build-${{ matrix.board }}/firmware.hex
