name: Check examples

on:
  push:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - 'examples/**'
      - 'ports/unix/**'
      - 'py/**'
      - 'shared/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  embedding:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Build
      run: make -C examples/embedding -f micropython_embed.mk && make -C examples/embedding
    - name: Run
      run: ./examples/embedding/embed | grep "hello world"

  embedding-full:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Build
      run: make -C examples/embedding-full -f micropython_embed.mk submodules && make -C examples/embedding-full -f micropython_embed.mk && make -C examples/embedding-full
    - name: Run
      run: ./examples/embedding-full/embed
