name: renesas-ra port

on:
  push:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - 'tools/**'
      - 'py/**'
      - 'extmod/**'
      - 'lib/**'
      - 'drivers/**'
      - 'ports/renesas-ra/**'

jobs:
  build_renesas_ra_board:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: source tools/ci.sh && ci_renesas_ra_setup
    - name: Build
      run: source tools/ci.sh && ci_renesas_ra_board_build

