# SPDX-FileCopyrightText: Copyright (c) 2019 Anthony Sottile
#
# SPDX-License-Identifier: MIT

name: pre-commit

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
    - name: Set up repository
      uses: actions/checkout@v3
      with:
        submodules: false
        fetch-depth: 1
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Set up submodules
      uses: ./.github/actions/deps/submodules
    - name: Set up external
      uses: ./.github/actions/deps/external
    - name: Install dependencies
      run: sudo apt-get install -y gettext uncrustify
    - name: Run pre-commit
      uses: pre-commit/action@v3.0.0
    - name: Make patch
      if: failure()
      run: git diff > ~/pre-commit.patch
    - name: Upload patch
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: patch
        path: ~/pre-commit.patch
